
dict_marca = {
    "APRILIA": "aprilia",
    "BENELLI": "benelli",
    "BETA": "beta",
    "BRP": "brp",
    "BMW": "bmw",
    "BUELL": "buell",
    "BULTACO": "bultaco",
    "CAGIVA": "cagiva",
    "CAN-AM": "can-am",
    "CFMOTO": "cfmoto",
    "CSR": "csr",
    "DAELIM": "daelim",
    "DERBI": "derbi",
    "DUCATI": "ducati",
    "GAS GAS": "gas_gas",
    "GILERA": "gilera",
    "GOES": "goes",
    "HANWAY": "hanway",
    "HARLEY DAVIDSON": "harley_davidson",
    "HONDA": "honda",
    "HUSABERG": "husaberg",
    "HUSQVARNA": "husqvarna",
    "HYOSUNG": "hyosung",
    "INDIAN": "indian",
    "KAWASAKI": "kawasaki",
    "KEEWAY": "keeway",
    "KSR MOTO": "ksr_moto",
    "KTM": "ktm",
    "KYMCO": "kymco",
    "LAMBRETTA": "lambretta",
    "LEONART": "leonart",
    "LINHAI": "linhai",
    "LML": "lml",
    "MALAGUTI": "malaguti",
    "MASH": "mash",
    "MONKEY BIKE": "monkey_bike",
    "MONTESA": "montesa",
    "MOTO GUZZI": "moto_guzzi",
    "MOTOR HISPANIA": "motor_hispania",
    "MTR": "mtr",
    "MV AGUSTA": "mv_agusta",
    "MXONDA": "mxonda",
    "OSSA": "ossa",
    "PEUGEOT": "peugeot",
    "PIAGGIO": "piaggio",
    "RIEJU": "rieju",
    "RIYA": "riya",
    "ROYAL ENFIELD": "royal_enfield",
    "SCOMADI": "scomadi",
    "SHERCO": "sherco",
    "SUMCO": "sumco",
    "SUZUKI": "suzuki",
    "SYM": "sym",
    "TGB": "tgb",
    "TM": "tm",
    "TRIUMPH": "triumph",
    "VESPA": "vespa",
    "VESPINO": "vespino",
    "VICTORY": "victory",
    "YAMAHA": "yamaha"
}

