dict_triumph = {
    "ADVENTURER 97": "adventurer_97",
    "AMERICA 900": "america_900",
    "America LT": "america_lt",
    "BONNEVILLE 50 aniversario": "bonneville_50_aniversario",
    "BONNEVILLE 900": "bonneville_900",
    "BONNEVILLE America": "bonneville_america",
    "BONNEVILLE Black": "bonneville_black",
    "BONNEVILLE SE": "bonneville_se",
    "BONNEVILLE SE 2-Tone": "bonneville_se_2-tone",
    "BONNEVILLE T100": "bonneville_t100",
    "Boneville": "boneville",
    "Bonneville Bobber": "bonneville_bobber",
    "Bonneville Speedmaster": "bonneville_speedmaster",
    "Bonneville T100 Black": "bonneville",
    "Bonneville T120": "bonneville_t120",
    "Bonneville T214": "bonneville_t214",
    "DAYTONA 600": "daytona_600",
    "DAYTONA 675 TRIPLE": "daytona_675_triple",
    "DAYTONA 675R": "daytona_675r",
    "DAYTONA 955 i": "daytona_955_i",
    "Daytona 660": "daytona_660",
    "Daytona Moto2 765 Limited Edition": "daytona_moto2_765_limited_edition",
    "Elvis Presley Limited Edition": "elvis_presley_limited_edition",
    "Legend TT": "legend_tt",
    "ROCKET 3 GT": "rocket_3",
    "ROCKET 3 R": "rocket",
    "ROCKET III": "rocket_iii",
    "ROCKET III Classic": "rocket_iii_classic",
    "ROCKET III Roadster ABS": "rocket_iii_roadster_abs",
    "ROCKET III Touring": "rocket_iii_touring",
    "SCRAMBLER EFI": "scrambler_efi",
    "SPEED Four": "speed_four",
    "SPEED TRIPLE": "speed_triple",
    "SPEED TRIPLE 15 aniversario": "speed_triple_15_aniversario",
    "SPEED TRIPLE ABS": "speed_triple_abs",
    "SPEED Triple R": "speed_triple_r",
    "SPRINT GT": "sprint_gt",
    "SPRINT ST": "sprint_st",
    "SPRINT ST 955i": "sprint_st_955i",
    "SPRINT ST ABS": "sprint_st_abs",
    "STREET TRIPLE": "street_triple",
    "STREET TRIPLE R": "street_triple_r",
    "Scrambler": "scrambler",
    "Scrambler 1200 XC": "scrambler_1200",
    "Scrambler 1200 XE": "scrambler_1200_xe",
    "Scrambler 400 X": "scrambler_400_x",
    "Scrambler 900": "scrambler_900",
    "Speed 400": "speed_400",
    "Speed Triple S": "speed_triple_s",
    "Speed Twin": "speed_twin",
    "Speed Twin 1200": "speed_twin_1200",
    "Speed Twin 900": "speed_twin_900",
    "Speedmaster 800": "speedmaster_800",
    "Speedmaster 900": "speedmaster_900",
    "Speedmaster 900 2-Tone": "speedmaster_900_2-tone",
    "Street Cup": "street_cup",
    "Street Scrambler": "street",
    "Street Triple 765 R": "street_triple_765",
    "Street Triple 95 CV ABS": "street_triple_95_cv_abs",
    "Street Triple ABS": "street_triple_abs",
    "Street Twin": "street_twin",
    "TF 250 E": "tf_250_e",
    "TF 250 X": "tf_250_x",
    "TF 450 RC Edition": "tf_450_rc_edition",
    "TIGER 1050": "tiger_1050",
    "TIGER 1050 ABS": "tiger_1050_abs",
    "TIGER 1050 Sport": "tiger_1050_sport",
    "TIGER 1200 XRT": "tiger_1200",
    "TIGER 800 ABS": "tiger_800_abs",
    "TIGER 800 XC": "tiger_800_xc",
    "TIGER 800 XC ABS": "tiger_800_xc_abs",
    "TIGER 800 XCX ABS": "tiger_800_xcx_abs",
    "TIGER 800 XR": "tiger_800",
    "TIGER 900 GT Pro": "tiger_900",
    "TIGER 955": "tiger_955",
    "TIGER Explorer 1200": "tiger_explorer_1200",
    "TIGER Explorer 1200 XC": "tiger_explorer_1200_xc",
    "TROPHY 1200": "trophy_1200",
    "TT 600": "tt_600",
    "Thruxton": "thruxton",
    "Thruxton EFI": "thruxton_efi",
    "Thruxton R": "thruxton",
    "Thruxton RS": "thruxton_rs",
    "Thunderbird 1600": "thunderbird_1600",
    "Thunderbird 1600 2-Tone": "thunderbird_1600_2-tone",
    "Thunderbird 900": "thunderbird_900",
    "Thunderbird 900 Sport": "thunderbird_900_sport",
    "Thunderbird LT": "thunderbird_lt",
    "Tiger 1200 GT PRO": "tiger_1200_gt",
    "Tiger 1200 Rally PRO": "tiger_1200_rally",
    "Tiger 800 XR X": "tiger_800_xr",
    "Tiger 800 XRT": "tiger_800_xrt",
    "Tiger 850 Sport": "tiger_850_sport",
    "Tiger Sport 660": "tiger_sport_660",
    "Tiger Sport 800": "tiger_sport_800",
    "Trident 660": "trident_660",
    "Trident 900": "trident_900",
    "Trophy SE": "trophy_se",
}

